### ISSUE TITLE
Call graph can't be generated

### ISSUE THREAD

**Issue by mrkafk** [amcfague/linesman#37]
I get this traceback:

	2016-02-22 18:02:07,076 ERROR channel.py:339  service              | Exception when serving /__profiler__/graph/dcf6b404-d985-11e5-8382-005056221eef--968350.png
	Traceback (most recent call last):
	  File "/export/home/myuser/mysite/ve/lib/python2.7/site-packages/waitress/channel.py", line 336, in service
		task.service()
	  File "/export/home/myuser/mysite/ve/lib/python2.7/site-packages/waitress/task.py", line 169, in service
		self.execute()
	  File "/export/home/myuser/mysite/ve/lib/python2.7/site-packages/waitress/task.py", line 388, in execute
		app_iter = self.channel.server.application(env, start_response)
	  File "/export/home/myuser/mysite/ve/lib/python2.7/site-packages/linesman/middleware.py", line 132, in __call__
		wsgi_app = self.render_graph(req)
	  File "/export/home/myuser/mysite/ve/lib/python2.7/site-packages/linesman/middleware.py", line 244, in render_graph
		draw_graph(graph, path)
	  File "/export/home/myuser/mysite/ve/lib/python2.7/site-packages/linesman/__init__.py", line 51, in draw_graph
		nx.to_agraph(graph).draw(output_path, prog="dot")
	AttributeError: 'module' object has no attribute 'to_agraph'

Dependencies: 

	networkx==1.11
	Pillow==3.1.1

**Comment by mrkafk** [comment]
Fix:
     _Looks like a duplicate of #30. The fix to pin networx to 1.7 worked for me too._

**Comment by amcfague** [comment]
Closing as duplicate.

**Comment by papachoco** [comment]
From https://github.com/networkx/networkx/issues/2365
In networkx 1.11
The function to_agraph is no longer exposed at the nx. level.
Now you must call nx.nx_agraph.to_agraph()
